
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.ParseException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HOME
 */
public class Age_Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Age_Calculator
     */
    public Age_Calculator() {
        initComponents();
        setVisible(true);
        setResizable(false);
        /*Calendar cal=Calendar.getInstance();
        int dd=cal.get(Calendar.DAY_OF_MONTH);
        DefaultComboBoxModel model1=(DefaultComboBoxModel) current_Date.getModel();
        model1.setSelectedItem(dd);
        int mm=cal.get(Calendar.MONTH);//System.out.print(mm);
        DefaultComboBoxModel model2=(DefaultComboBoxModel) current_Month.getModel();
        model2.setSelectedItem(mm+1);
        int yyyy=cal.get(Calendar.YEAR);
        DefaultComboBoxModel model3=(DefaultComboBoxModel) current_Year.getModel();
        model3.setSelectedItem(yyyy);*/
        setTitle("AGE CALCULATOR");
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/4-this.getSize().height/4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        current_Date = new javax.swing.JComboBox();
        birth_Date = new javax.swing.JComboBox();
        birth_Month = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        birth_Year = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        current_Month = new javax.swing.JComboBox();
        current_Year = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        go = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        Age_In_Years = new javax.swing.JLabel();
        Your_Age_In_Days = new javax.swing.JLabel();
        Your_Age_In_Hours = new javax.swing.JLabel();
        Your_Age_In_Minute = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jButton2.setBackground(new java.awt.Color(153, 153, 255));
        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 102));
        jButton2.setText("main menu :");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("Statistic Calculator");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 3, true));
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel1KeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 80)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Age Calculator");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Calculate Your Age from Date of Birth");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Today's Date is :");

        current_Date.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        current_Date.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        current_Date.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        current_Date.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        current_Date.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                current_DateMouseClicked(evt);
            }
        });
        current_Date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                current_DateActionPerformed(evt);
            }
        });
        current_Date.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                current_DateKeyPressed(evt);
            }
        });

        birth_Date.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        birth_Date.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        birth_Date.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        birth_Date.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        birth_Date.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                birth_DateMouseClicked(evt);
            }
        });
        birth_Date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birth_DateActionPerformed(evt);
            }
        });

        birth_Month.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        birth_Month.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        birth_Month.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        birth_Month.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        birth_Month.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                birth_MonthMouseClicked(evt);
            }
        });
        birth_Month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birth_MonthActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Select Your Date of Birth :");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Date");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Date");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Month");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("Year");

        birth_Year.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        birth_Year.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "1901", "1902", "1903", "1904", "1905", "1906", "1907", "1908", "1909", "1910", "1911", "1912", "1913", "1914", "1915", "1916", "1917", "1918", "1919", "1920", "1921", "1922", "1923", "1924", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015" }));
        birth_Year.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        birth_Year.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        birth_Year.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                birth_YearMouseClicked(evt);
            }
        });
        birth_Year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birth_YearActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("Month");

        current_Month.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        current_Month.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        current_Month.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        current_Month.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        current_Month.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                current_MonthMouseClicked(evt);
            }
        });
        current_Month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                current_MonthActionPerformed(evt);
            }
        });

        current_Year.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        current_Year.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "1901", "1902", "1903", "1904", "1905", "1906", "1907", "1908", "1909", "1910", "1911", "1912", "1913", "1914", "1915", "1916", "1917", "1918", "1919", "1920", "1921", "1922", "1923", "1924", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015" }));
        current_Year.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        current_Year.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        current_Year.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                current_YearMouseClicked(evt);
            }
        });
        current_Year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                current_YearActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("Year");

        go.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        go.setText("GO");
        go.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        go.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goActionPerformed(evt);
            }
        });
        go.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                goFocusGained(evt);
            }
        });

        reset.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        reset.setText("Reset");
        reset.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        reset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        Age_In_Years.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Age_In_Years.setText("Your Age is : ");
        Age_In_Years.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Your_Age_In_Days.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Your_Age_In_Days.setText("Your Age in Days : ");
        Your_Age_In_Days.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Your_Age_In_Hours.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Your_Age_In_Hours.setText("Your Age in Hours : ");
        Your_Age_In_Hours.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Your_Age_In_Minute.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Your_Age_In_Minute.setText("Your Age in Minutes : ");
        Your_Age_In_Minute.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton3.setBackground(new java.awt.Color(153, 153, 255));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 102));
        jButton3.setText("Main Menu ");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButton3FocusGained(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Arithmetic Calculator");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(current_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(birth_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))
                                .addGap(18, 59, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(birth_Month, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel16))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(current_Month, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel18)))
                                .addGap(18, 59, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(birth_Year, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19)
                                    .addComponent(current_Year, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(Age_In_Years, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Your_Age_In_Days, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Your_Age_In_Hours, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Your_Age_In_Minute, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(go, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {birth_Date, birth_Month, birth_Year, current_Year});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {current_Date, current_Month});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(current_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(current_Month, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(current_Year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(birth_Month, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(birth_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(birth_Year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(go, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reset))
                .addGap(30, 30, 30)
                .addComponent(Age_In_Years, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Your_Age_In_Days, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Your_Age_In_Hours, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Your_Age_In_Minute, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {current_Month, current_Year});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {birth_Date, birth_Month, birth_Year, current_Date});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {go, reset});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void current_DateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_current_DateMouseClicked
        // TODO add your handling code here:
        current_Date.setBackground(Color.WHITE);
    }//GEN-LAST:event_current_DateMouseClicked

    private void current_DateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_current_DateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_current_DateActionPerformed

    private void current_DateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_current_DateKeyPressed
        // TODO add your handling code here:
        if ( ((evt.getKeyChar() == 10))){go.setFocusable(true); go.requestFocus(true);}
    }//GEN-LAST:event_current_DateKeyPressed

    private void birth_DateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_birth_DateMouseClicked
        // TODO add your handling code here:
        birth_Date.setBackground(Color.WHITE);
    }//GEN-LAST:event_birth_DateMouseClicked

    private void birth_DateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birth_DateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_birth_DateActionPerformed

    private void birth_MonthMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_birth_MonthMouseClicked
        // TODO add your handling code here:
        birth_Month.setBackground(Color.WHITE);
    }//GEN-LAST:event_birth_MonthMouseClicked

    private void birth_MonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birth_MonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_birth_MonthActionPerformed

    private void birth_YearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_birth_YearMouseClicked
        // TODO add your handling code here:
        birth_Year.setBackground(Color.WHITE);
    }//GEN-LAST:event_birth_YearMouseClicked

    private void birth_YearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birth_YearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_birth_YearActionPerformed

    private void current_MonthMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_current_MonthMouseClicked
        // TODO add your handling code here:
        current_Month.setBackground(Color.WHITE);
    }//GEN-LAST:event_current_MonthMouseClicked

    private void current_MonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_current_MonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_current_MonthActionPerformed

    private void current_YearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_current_YearMouseClicked
        // TODO add your handling code here:
        current_Year.setBackground(Color.WHITE);
    }//GEN-LAST:event_current_YearMouseClicked

    private void current_YearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_current_YearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_current_YearActionPerformed

    private void goActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goActionPerformed
        // TODO add your handling code here:
        int c_date=0,c_month=0,c_year=0;
        int b_date=0,b_month=0,b_year=0;
        int bflag = 0,cflag=0;
        String ComboBox_Item;
        Age_In_Years.setText("Your Age is : ");
        Your_Age_In_Days.setText("Your Age in Days : ");
        Your_Age_In_Hours.setText("Your Age in Hours : ");
        Your_Age_In_Minute.setText("Your Age in Minutes : ");

        if(current_Date.getSelectedItem()=="Select" || current_Month.getSelectedItem()=="Select" || current_Year.getSelectedItem()=="Select" ||
            birth_Date.getSelectedItem()=="Select" || birth_Month.getSelectedItem()=="Select" || birth_Year.getSelectedItem()=="Select"){
            if(current_Date.getSelectedItem()=="Select"){current_Date.setBackground(Color.YELLOW);}
            if(current_Month.getSelectedItem()=="Select"){current_Month.setBackground(Color.YELLOW);}
            if(current_Year.getSelectedItem()=="Select"){current_Year.setBackground(Color.YELLOW);}
            if(birth_Date.getSelectedItem()=="Select"){birth_Date.setBackground(Color.YELLOW);}
            if(birth_Month.getSelectedItem()=="Select"){birth_Month.setBackground(Color.YELLOW);}
            if(birth_Year.getSelectedItem()=="Select"){birth_Year.setBackground(Color.YELLOW);}
            JOptionPane.showMessageDialog(null,"Select Your Date....!");
        }

        else{
            ComboBox_Item=(String) current_Date.getSelectedItem();
            c_date=Integer.parseInt(ComboBox_Item);System.out.println(c_date);

            ComboBox_Item=(String) current_Month.getSelectedItem();
            c_month=Integer.parseInt(ComboBox_Item);System.out.println(c_month);

            ComboBox_Item=(String) current_Year.getSelectedItem();
            c_year=Integer.parseInt(ComboBox_Item);System.out.println(c_year);

            ComboBox_Item=(String) birth_Date.getSelectedItem();
            b_date=Integer.parseInt(ComboBox_Item);

            ComboBox_Item=(String) birth_Month.getSelectedItem();
            b_month=Integer.parseInt(ComboBox_Item);

            ComboBox_Item=(String) birth_Year.getSelectedItem();
            b_year=Integer.parseInt(ComboBox_Item);

            if( c_year % 400 == 0 || b_year % 400 == 0){cflag = 1; bflag = 1;}
            else if (c_year % 100 == 0 || b_year % 100 == 0){cflag = 0; bflag = 0;}
            else if (c_year % 4 == 0 || b_year % 4 == 0){cflag = 1; bflag = 1;}

            if((c_month==4 || c_month==6 || c_month==9 ||c_month==11) && ((c_date>30))){JOptionPane.showMessageDialog(null,"Current date is Invalid");}
            else if((cflag==1) && (c_month==2) && ((c_date>29))){JOptionPane.showMessageDialog(null,"Current date is Invalid");}
            else if((cflag==0) && (c_month==2) && ((c_date>28))){JOptionPane.showMessageDialog(null,"Current date is Invalid");}

            else if((b_month==4 || b_month==6 || b_month==9 ||b_month==11) && ((b_date>30))){JOptionPane.showMessageDialog(null,"Birth date is Invalid");}
            else if((bflag==1) && (b_month==2) && ((b_date>29))){JOptionPane.showMessageDialog(null,"Birth date is Invalid");}
            else if((bflag==0) && (b_month==2) && ((b_date>28))){JOptionPane.showMessageDialog(null,"Birth date is Invalid");}

            else {
                if (c_date==b_date && c_month==b_month && c_year==b_year){
                    Calendar now = Calendar.getInstance();
                    JOptionPane.showMessageDialog(null,"Happy Birthday...!");
                }

                else if (c_year==b_year){
                    if (c_month==b_month && c_date<b_date){JOptionPane.showMessageDialog(null,"Select your date of birth date less than current date");}
                    if (c_month<b_month){JOptionPane.showMessageDialog(null,"Select your date of birth month less than current month");}
                }

                else if(c_year<b_year){JOptionPane.showMessageDialog(null,"Select your date of birth year less than current year");}

                else {
                    AgeCalculator obj=new AgeCalculator(c_date,c_month,c_year,b_date,b_month,b_year);
                    try {

                        String age=obj.computeAge ();
                        Age_In_Years.setText(Age_In_Years.getText()+age);

                        long days=obj.days();
                        Your_Age_In_Days.setText(Your_Age_In_Days.getText()+" "+days+" days since your birth ");

                        long hours=obj.hours();
                        Your_Age_In_Hours.setText(Your_Age_In_Hours.getText()+" "+hours+" hours approximately since your birth ");

                        long minutes=obj.minutes();
                        Your_Age_In_Minute.setText(Your_Age_In_Minute.getText()+" "+minutes+" minutes approximately since your birth ");

                    } catch (ParseException ex) {
                        Logger.getLogger(Age_Calculator.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
    }//GEN-LAST:event_goActionPerformed

    private void goFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_goFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_goFocusGained

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        current_Date.setBackground(Color.WHITE);current_Date.setSelectedIndex(0);
        current_Month.setBackground(Color.WHITE);current_Month.setSelectedIndex(0);
        current_Year.setBackground(Color.WHITE);current_Year.setSelectedIndex(0);
        birth_Date.setBackground(Color.WHITE);birth_Date.setSelectedIndex(0);
        birth_Month.setBackground(Color.WHITE);birth_Month.setSelectedIndex(0);
        birth_Year.setBackground(Color.WHITE);birth_Year.setSelectedIndex(0);
        Age_In_Years.setText("Your Age is : ");
        Your_Age_In_Days.setText("Your Age in Days : ");
        Your_Age_In_Hours.setText("Your Age in Hours : ");
        Your_Age_In_Minute.setText("Your Age in Minutes : ");
    }//GEN-LAST:event_resetActionPerformed

    private void jPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyPressed
        // TODO add your handling code here:
        if ( ((evt.getKeyChar() == 10))){go.setFocusable(true); go.requestFocus(true);}
    }//GEN-LAST:event_jPanel1KeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        MAIN_MENU obj=new MAIN_MENU();
        obj.setVisible(true);
        CloseFrame();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton3FocusGained
        // TODO add your handling code here:
        /*Calendar cal=Calendar.getInstance();
        int p=cal.get(Calendar.DAY_OF_MONTH);
        DefaultComboBoxModel model1=(DefaultComboBoxModel) current_Date.getModel();
        model1.setSelectedItem(p);
        int q=cal.get(Calendar.MONTH)+1;//System.out.print(mm);
        DefaultComboBoxModel model2=(DefaultComboBoxModel) current_Month.getModel();
        model2setSelectedItem(q);
        int r=cal.get(Calendar.YEAR);
        DefaultComboBoxModel model3=(DefaultComboBoxModel) current_Year.getModel();
        model3.setSelectedItem(r);*/
    }//GEN-LAST:event_jButton3FocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Age_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Age_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Age_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Age_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Age_Calculator().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Age_In_Years;
    private javax.swing.JLabel Your_Age_In_Days;
    private javax.swing.JLabel Your_Age_In_Hours;
    private javax.swing.JLabel Your_Age_In_Minute;
    private javax.swing.JComboBox birth_Date;
    private javax.swing.JComboBox birth_Month;
    private javax.swing.JComboBox birth_Year;
    private javax.swing.JComboBox current_Date;
    private javax.swing.JComboBox current_Month;
    private javax.swing.JComboBox current_Year;
    private javax.swing.JButton go;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton reset;
    // End of variables declaration//GEN-END:variables

    private void CloseFrame() {
        super.dispose();
    }
}
