
import java.awt.Dimension;
import java.awt.Toolkit;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HOME
 */
public class GeometricCalculator extends javax.swing.JFrame {

    /**
     * Creates new form GeometricCalculator
     */
    public GeometricCalculator() {
        initComponents();
        setVisible(true);
        setResizable(false);
        setTitle("GEOMETRIC CALCULATOR");
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Circle_Solver = new javax.swing.JButton();
        Triangle_Solver = new javax.swing.JButton();
        Parallelogram_Solver = new javax.swing.JButton();
        Rhombus_Solver = new javax.swing.JButton();
        Square_Solver = new javax.swing.JButton();
        Rectangle_Solver = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 3, true));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 90)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Geometric Calculator");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Circle_Solver.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Circle_Solver.setText("Circle Solver");
        Circle_Solver.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Circle_Solver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Circle_Solver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Circle_SolverActionPerformed(evt);
            }
        });
        Circle_Solver.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Circle_SolverKeyPressed(evt);
            }
        });

        Triangle_Solver.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Triangle_Solver.setText("Triangle Solver");
        Triangle_Solver.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Triangle_Solver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Triangle_Solver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Triangle_SolverActionPerformed(evt);
            }
        });
        Triangle_Solver.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Triangle_SolverKeyPressed(evt);
            }
        });

        Parallelogram_Solver.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Parallelogram_Solver.setText("Parallelogram Solver");
        Parallelogram_Solver.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Parallelogram_Solver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Parallelogram_Solver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Parallelogram_SolverActionPerformed(evt);
            }
        });
        Parallelogram_Solver.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Parallelogram_SolverKeyPressed(evt);
            }
        });

        Rhombus_Solver.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Rhombus_Solver.setText("Rhombus Solver");
        Rhombus_Solver.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Rhombus_Solver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Rhombus_Solver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rhombus_SolverActionPerformed(evt);
            }
        });
        Rhombus_Solver.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Rhombus_SolverKeyPressed(evt);
            }
        });

        Square_Solver.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Square_Solver.setText("Square Solver");
        Square_Solver.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Square_Solver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Square_Solver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Square_SolverActionPerformed(evt);
            }
        });
        Square_Solver.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Square_SolverKeyPressed(evt);
            }
        });

        Rectangle_Solver.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Rectangle_Solver.setText("Rectangle Solver");
        Rectangle_Solver.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Rectangle_Solver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Rectangle_Solver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rectangle_SolverActionPerformed(evt);
            }
        });
        Rectangle_Solver.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Rectangle_SolverKeyPressed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 102));
        jButton4.setText("Main Menu");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton4KeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("Geometric Calculator");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Parallelogram_Solver)
                            .addComponent(Circle_Solver, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Rectangle_Solver, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Triangle_Solver, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Rhombus_Solver)
                    .addComponent(Square_Solver, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Circle_Solver, Parallelogram_Solver, Rectangle_Solver, Rhombus_Solver, Square_Solver, Triangle_Solver});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Circle_Solver, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Rhombus_Solver))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Parallelogram_Solver)
                    .addComponent(Square_Solver))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rectangle_Solver)
                    .addComponent(Triangle_Solver, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Circle_Solver, Parallelogram_Solver, Rectangle_Solver, Rhombus_Solver, Square_Solver, Triangle_Solver});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Circle_SolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Circle_SolverActionPerformed
        // TODO add your handling code here:
        Circle_Solver obj=new Circle_Solver();
        obj.setVisible(true);
        CloseFrame();
    }//GEN-LAST:event_Circle_SolverActionPerformed

    private void Triangle_SolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Triangle_SolverActionPerformed
        // TODO add your handling code here:
        Triangle_Solver obj=new Triangle_Solver();
        obj.setVisible(true);
        CloseFrame();
    }//GEN-LAST:event_Triangle_SolverActionPerformed

    private void Parallelogram_SolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Parallelogram_SolverActionPerformed
        // TODO add your handling code here:
        Parallalogram_Solver obj=new Parallalogram_Solver();
        obj.setVisible(true);
        CloseFrame();
    }//GEN-LAST:event_Parallelogram_SolverActionPerformed

    private void Rhombus_SolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rhombus_SolverActionPerformed
        // TODO add your handling code here:
        Rhombus_Solver obj=new Rhombus_Solver();
        obj.setVisible(true);
        CloseFrame();
    }//GEN-LAST:event_Rhombus_SolverActionPerformed

    private void Square_SolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Square_SolverActionPerformed
        // TODO add your handling code here:
        Square_Solver obj=new Square_Solver();
        obj.setVisible(true);
        CloseFrame();
    }//GEN-LAST:event_Square_SolverActionPerformed

    private void Rectangle_SolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rectangle_SolverActionPerformed
        // TODO add your handling code here:
        Rectangle_Solver obj=new Rectangle_Solver();
        obj.setVisible(true);
        CloseFrame();
    }//GEN-LAST:event_Rectangle_SolverActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        MAIN_MENU obj=new MAIN_MENU();
        obj.setVisible(true);
        CloseFrame();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void Circle_SolverKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Circle_SolverKeyPressed
        // TODO add your handling code here:
        if((evt.getKeyChar()==10)){
            Circle_Solver obj=new Circle_Solver();
            obj.setVisible(true);
            CloseFrame();
        }
    }//GEN-LAST:event_Circle_SolverKeyPressed

    private void Triangle_SolverKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Triangle_SolverKeyPressed
        // TODO add your handling code here:
        if((evt.getKeyChar()==10)){
            Triangle_Solver obj=new Triangle_Solver();
            obj.setVisible(true);
            CloseFrame();
        }
    }//GEN-LAST:event_Triangle_SolverKeyPressed

    private void Rectangle_SolverKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Rectangle_SolverKeyPressed
        // TODO add your handling code here:
        if((evt.getKeyChar()==10)){
            Rectangle_Solver obj=new Rectangle_Solver();
            obj.setVisible(true);
            CloseFrame();
        }
    }//GEN-LAST:event_Rectangle_SolverKeyPressed

    private void Parallelogram_SolverKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Parallelogram_SolverKeyPressed
        // TODO add your handling code here:
        if((evt.getKeyChar()==10)){
            Parallalogram_Solver obj=new Parallalogram_Solver();
            obj.setVisible(true);
            CloseFrame();
        }
    }//GEN-LAST:event_Parallelogram_SolverKeyPressed

    private void Square_SolverKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Square_SolverKeyPressed
        // TODO add your handling code here:
        if((evt.getKeyChar()==10)){
            Square_Solver obj=new Square_Solver();
            obj.setVisible(true);
            CloseFrame();
        }
    }//GEN-LAST:event_Square_SolverKeyPressed

    private void Rhombus_SolverKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Rhombus_SolverKeyPressed
        // TODO add your handling code here:
        if((evt.getKeyChar()==10)){
            Rhombus_Solver obj=new Rhombus_Solver();
            obj.setVisible(true);
            CloseFrame();
        }
    }//GEN-LAST:event_Rhombus_SolverKeyPressed

    private void jButton4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton4KeyPressed
        // TODO add your handling code here:
        if((evt.getKeyChar()==10)){
            MAIN_MENU obj=new MAIN_MENU();
            obj.setVisible(true);
            CloseFrame();
        }
    }//GEN-LAST:event_jButton4KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GeometricCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GeometricCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GeometricCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GeometricCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GeometricCalculator().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Circle_Solver;
    private javax.swing.JButton Parallelogram_Solver;
    private javax.swing.JButton Rectangle_Solver;
    private javax.swing.JButton Rhombus_Solver;
    private javax.swing.JButton Square_Solver;
    private javax.swing.JButton Triangle_Solver;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void CloseFrame() {
        super.dispose();
    }
}
