
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HOME
 */
public class Linear_Equation_Solver extends javax.swing.JFrame {
    int a1=0,b1=0,c1=0,a2=0,b2=0,c2=0;
    float x=0,y=0;
    String ans,p;

    /**
     * Creates new form Linear_Equation_Solver
     */
    public Linear_Equation_Solver() {
        initComponents();
        setVisible(true);
        setResizable(false);
        setTitle("LINEAR EQUATION SOLVER");
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        sign1 = new javax.swing.JComboBox();
        A1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        sign2 = new javax.swing.JComboBox();
        B1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sign4 = new javax.swing.JComboBox();
        A2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        sign5 = new javax.swing.JComboBox();
        B2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        C2 = new javax.swing.JTextField();
        C1 = new javax.swing.JTextField();
        sign3 = new javax.swing.JComboBox();
        sign6 = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        Result = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        calculate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 3, true));
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel1KeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 80)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Linear Equation Solver");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        sign1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        sign1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "+", "-" }));
        sign1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sign1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        A1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        A1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        A1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        A1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A1MouseClicked(evt);
            }
        });
        A1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                A1KeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        sign2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        sign2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "+", "-" }));
        sign2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sign2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        B1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        B1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        B1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        B1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B1MouseClicked(evt);
            }
        });
        B1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                B1KeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Y");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("=");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        sign4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        sign4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "+", "-" }));
        sign4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sign4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        A2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        A2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        A2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        A2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A2MouseClicked(evt);
            }
        });
        A2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                A2KeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("X");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        sign5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        sign5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "+", "-" }));
        sign5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sign5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        B2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        B2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        B2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        B2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B2MouseClicked(evt);
            }
        });
        B2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                B2KeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Y");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("=");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("Reset");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        C2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        C2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        C2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        C2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                C2MouseClicked(evt);
            }
        });
        C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C2ActionPerformed(evt);
            }
        });
        C2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                C2KeyPressed(evt);
            }
        });

        C1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        C1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        C1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        C1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                C1MouseClicked(evt);
            }
        });
        C1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                C1KeyPressed(evt);
            }
        });

        sign3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        sign3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "+", "-" }));
        sign3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sign3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        sign6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        sign6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "+", "-" }));
        sign6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sign6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        Result.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Result.setText("Result : ");
        Result.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Result, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Result, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        jButton2.setBackground(new java.awt.Color(153, 153, 255));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 102));
        jButton2.setText("Main Menu");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 102));
        jLabel8.setText("Linear Equation Solver    EXP: 3x + 2y = 17  and  2x + 3y = 18");

        calculate.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        calculate.setText("Calculate");
        calculate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        calculate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateActionPerformed(evt);
            }
        });
        calculate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                calculateFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sign4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(A2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(sign5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sign1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(A1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(sign2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(calculate, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sign6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(C2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sign3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(C1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(140, 140, 140))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {sign1, sign2, sign3, sign4, sign5, sign6});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {A1, B1, B2, C1, C2});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel3, jLabel5, jLabel6});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sign1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(A1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sign2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(C1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sign3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(B2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sign4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(A2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sign5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(C2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sign6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(calculate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {sign1, sign2, sign3, sign4, sign5, sign6});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {A1, B1, B2, C1, C2});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel3, jLabel5, jLabel6});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void A1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A1MouseClicked
        // TODO add your handling code here:
        A1.setBackground(Color.WHITE);
    }//GEN-LAST:event_A1MouseClicked

    private void A1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_A1KeyPressed
        // TODO add your handling code here:
        int l = A1.getText().length();
        if ( (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') || (evt.getKeyChar() == 8) || (evt.getKeyChar()==10)) {
            if((l<=2) || (evt.getKeyChar() == 8) ){
                A1.setEditable(true);
                if((evt.getKeyChar() == 10)){
                    p="A1";
                    calculate.requestFocus();calculate.setFocusable(true);
                }
            }
            else{
                A1.setEditable(false);
            }
        }
        else {
            A1.setEditable(false);
        }
    }//GEN-LAST:event_A1KeyPressed

    private void B1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B1MouseClicked
        // TODO add your handling code here:
        B1.setBackground(Color.WHITE);
    }//GEN-LAST:event_B1MouseClicked

    private void B1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_B1KeyPressed
        // TODO add your handling code here:
        int l = B1.getText().length();
        if ( (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') || (evt.getKeyChar() == 8) ||(evt.getKeyChar()==10)) {
            if((l<=2) || (evt.getKeyChar() == 8) ){
                B1.setEditable(true);
                if((evt.getKeyChar() == 10)){
                    p="B1";
                    calculate.requestFocus();calculate.setFocusable(true);
                }
            }
            else{

                B1.setEditable(false);
            }
        }
        else {
            B1.setEditable(false);
        }
    }//GEN-LAST:event_B1KeyPressed

    private void A2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A2MouseClicked
        // TODO add your handling code here:
        A2.setBackground(Color.WHITE);
    }//GEN-LAST:event_A2MouseClicked

    private void A2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_A2KeyPressed
        // TODO add your handling code here:
        int l = A2.getText().length();
        if ( (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') || (evt.getKeyChar() == 8) ||(evt.getKeyChar()==10)) {
            if((l<=2) || (evt.getKeyChar() == 8) ){
                A2.setEditable(true);
                if((evt.getKeyChar() == 10)){
                    p="A2";
                    calculate.requestFocus();calculate.setFocusable(true);
                }
            }
            else{

                A2.setEditable(false);
            }
        }
        else {
            A2.setEditable(false);
        }
    }//GEN-LAST:event_A2KeyPressed

    private void B2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B2MouseClicked
        // TODO add your handling code here:
        B2.setBackground(Color.WHITE);
    }//GEN-LAST:event_B2MouseClicked

    private void B2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_B2KeyPressed
        // TODO add your handling code here:
        int l = B2.getText().length();
        if ( (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') || (evt.getKeyChar() == 8) || (evt.getKeyChar()==10)) {
            if((l<=2) || (evt.getKeyChar() == 8) ){
                B2.setEditable(true);
                if((evt.getKeyChar() == 10)){
                    p="B2";
                    calculate.requestFocus();calculate.setFocusable(true);
                }
            }
            else{

                B2.setEditable(false);
            }
        }
        else {
            B2.setEditable(false);
        }
    }//GEN-LAST:event_B2KeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        A1.setText("");A1.setBackground(Color.WHITE);
        B1.setText("");B1.setBackground(Color.WHITE);
        C1.setText("");C1.setBackground(Color.WHITE);
        A2.setText("");A2.setBackground(Color.WHITE);
        B2.setText("");B2.setBackground(Color.WHITE);
        C2.setText("");C2.setBackground(Color.WHITE);
        Result.setText("Result : ");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void C2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C2MouseClicked
        // TODO add your handling code here:
        C2.setBackground(Color.WHITE);
    }//GEN-LAST:event_C2MouseClicked

    private void C2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C2ActionPerformed

    private void C2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_C2KeyPressed
        // TODO add your handling code here:
        int l = C2.getText().length();
        if ( (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') || (evt.getKeyChar() == 8) || (evt.getKeyChar()==10)) {
            if((l<=2) || (evt.getKeyChar() == 8) ){
                C2.setEditable(true);
                if((evt.getKeyChar() == 10)){
                    p="C2";
                    calculate.requestFocus();calculate.setFocusable(true);
                }
            }
            else{

                C2.setEditable(false);
            }
        }
        else {
            C2.setEditable(false);
        }
    }//GEN-LAST:event_C2KeyPressed

    private void C1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C1MouseClicked
        // TODO add your handling code here:
        C1.setBackground(Color.WHITE);
    }//GEN-LAST:event_C1MouseClicked

    private void C1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_C1KeyPressed
        // TODO add your handling code here:
        int l = C1.getText().length();
        if ( (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') || (evt.getKeyChar() == 8) ||(evt.getKeyChar()==10)) {
            if((l<=2) || (evt.getKeyChar() == 8) ){
                C1.setEditable(true);
                if((evt.getKeyChar() == 10)){
                    p="C1";
                    calculate.requestFocus();calculate.setFocusable(true);
                }
            }
            else{

                C1.setEditable(false);
            }
        }
        else {
            C1.setEditable(false);
        }
    }//GEN-LAST:event_C1KeyPressed

    private void jPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1KeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        MAIN_MENU obj=new MAIN_MENU();
        obj.setVisible(true);
        CloseFrame();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateActionPerformed
        // TODO add your handling code here:
        if("".equals(A1.getText()) || "".equals(B1.getText()) || "".equals(C1.getText()) || "".equals(A2.getText()) || "".equals(B2.getText()) || "".equals(C2.getText())){
            JOptionPane.showMessageDialog(null,"ALL FIELDS SHOULD BE FILLED");
            if(A1.getText().length()==0){A1.setBackground(Color.YELLOW);}
            if(B1.getText().length()==0){B1.setBackground(Color.YELLOW);}
            if(C1.getText().length()==0){C1.setBackground(Color.YELLOW);}
            if(A2.getText().length()==0){A2.setBackground(Color.YELLOW);}
            if(B2.getText().length()==0){B2.setBackground(Color.YELLOW);}
            if(C2.getText().length()==0){C2.setBackground(Color.YELLOW);}
        }
        else{
            Result.setText("Result : ");
            a1=Integer.parseInt(A1.getText());
            b1=Integer.parseInt(B1.getText());
            c1=Integer.parseInt(C1.getText());
            a2=Integer.parseInt(A2.getText());
            b2=Integer.parseInt(B2.getText());
            c2=Integer.parseInt(C2.getText());
            if(sign1.getSelectedItem()=="-"){a1=(-1)*a1;}
            if(sign2.getSelectedItem()=="-"){b1=(-1)*b1;}
            if(sign3.getSelectedItem()=="-"){c1=(-1)*c1;}
            if(sign4.getSelectedItem()=="-"){a2=(-1)*a2;}
            if(sign5.getSelectedItem()=="-"){b2=(-1)*b2;}
            if(sign6.getSelectedItem()=="-"){c2=(-1)*c2;}
            LinearEauationSolver obj= new LinearEauationSolver(a1,b1,c1,a2,b2,c2);

            ans=obj.computeEquations();
            Result.setText(ans);

        }
    }//GEN-LAST:event_calculateActionPerformed

    private void calculateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_calculateFocusGained
        // TODO add your handling code here:
        if("".equals(A1.getText()) || "".equals(B1.getText()) || "".equals(C1.getText()) || "".equals(A2.getText()) || "".equals(B2.getText()) || "".equals(C2.getText())){
            A1.requestFocus();A1.setFocusable(true);
            JOptionPane.showMessageDialog(null,"ALL FIELDS SHOULD BE FILLED");
            if(A1.getText().length()==0){A1.setBackground(Color.YELLOW);}
            if(B1.getText().length()==0){B1.setBackground(Color.YELLOW);}
            if(C1.getText().length()==0){C1.setBackground(Color.YELLOW);}
            if(A2.getText().length()==0){A2.setBackground(Color.YELLOW);}
            if(B2.getText().length()==0){B2.setBackground(Color.YELLOW);}
            if(C2.getText().length()==0){C2.setBackground(Color.YELLOW);}
            
            if("A1".equals(p)){calculate.setFocusable(false);A1.requestFocus();A1.setFocusable(true);}
            if("B1".equals(p)){calculate.setFocusable(false);B1.requestFocus();B1.setFocusable(true);}
            if("C1".equals(p)){calculate.setFocusable(false);C1.requestFocus();C1.setFocusable(true);}
            if("A2".equals(p)){calculate.setFocusable(false);A2.requestFocus();A2.setFocusable(true);}
            if("B2".equals(p)){calculate.setFocusable(false);B2.requestFocus();B2.setFocusable(true);}
            if("C2".equals(p)){calculate.setFocusable(false);C2.requestFocus();C2.setFocusable(true);}
            
        }
        else{
            Result.setText("Result : ");
            a1=Integer.parseInt(A1.getText());
            b1=Integer.parseInt(B1.getText());
            c1=Integer.parseInt(C1.getText());
            a2=Integer.parseInt(A2.getText());
            b2=Integer.parseInt(B2.getText());
            c2=Integer.parseInt(C2.getText());
            if(sign1.getSelectedItem()=="-"){a1=(-1)*a1;}
            if(sign2.getSelectedItem()=="-"){b1=(-1)*b1;}
            if(sign3.getSelectedItem()=="-"){c1=(-1)*c1;}
            if(sign4.getSelectedItem()=="-"){a2=(-1)*a2;}
            if(sign5.getSelectedItem()=="-"){b2=(-1)*b2;}
            if(sign6.getSelectedItem()=="-"){c2=(-1)*c2;}
            LinearEauationSolver obj= new LinearEauationSolver(a1,b1,c1,a2,b2,c2);
            ans=obj.computeEquations();
            Result.setText(ans);

        }
    }//GEN-LAST:event_calculateFocusGained

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar()==10){
            A1.setText("");A1.setBackground(Color.WHITE);
            B1.setText("");B1.setBackground(Color.WHITE);
            C1.setText("");C1.setBackground(Color.WHITE);
            A2.setText("");A2.setBackground(Color.WHITE);
            B2.setText("");B2.setBackground(Color.WHITE);
            C2.setText("");C2.setBackground(Color.WHITE);
            Result.setText("Result : ");
        }
    }//GEN-LAST:event_jButton1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Linear_Equation_Solver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Linear_Equation_Solver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Linear_Equation_Solver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Linear_Equation_Solver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Linear_Equation_Solver().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField A1;
    private javax.swing.JTextField A2;
    private javax.swing.JTextField B1;
    private javax.swing.JTextField B2;
    private javax.swing.JTextField C1;
    private javax.swing.JTextField C2;
    private javax.swing.JLabel Result;
    private javax.swing.JButton calculate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox sign1;
    private javax.swing.JComboBox sign2;
    private javax.swing.JComboBox sign3;
    private javax.swing.JComboBox sign4;
    private javax.swing.JComboBox sign5;
    private javax.swing.JComboBox sign6;
    // End of variables declaration//GEN-END:variables

    private void CloseFrame() {
        super.dispose();
    }
}
