
import java.awt.Dimension;
import java.awt.Toolkit;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HOME
 */
public class MAIN_MENU extends javax.swing.JFrame {

    /**
     * Creates new form MAIN_MENU
     */
    public MAIN_MENU() {
        initComponents();
        setVisible(true);
        setResizable(false);
        setTitle("MAIN MENU");
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Arithmetic_Calculator = new javax.swing.JButton();
        Quadretic_Equation_Solver = new javax.swing.JButton();
        Trignometric_Calculator = new javax.swing.JButton();
        Geometric_Calculator = new javax.swing.JButton();
        Unit_Convertor = new javax.swing.JButton();
        Base_Convertor = new javax.swing.JButton();
        Age_Calculator = new javax.swing.JButton();
        Linear_Equation_Solver = new javax.swing.JButton();
        Statistic_Calculator = new javax.swing.JButton();
        Truth_Table_Designer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 3, true));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 90)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Main Menu");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Arithmetic_Calculator.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Arithmetic_Calculator.setText("Arithmetic Calculator");
        Arithmetic_Calculator.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Arithmetic_Calculator.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Arithmetic_Calculator.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Arithmetic_CalculatorMouseClicked(evt);
            }
        });
        Arithmetic_Calculator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Arithmetic_CalculatorActionPerformed(evt);
            }
        });
        Arithmetic_Calculator.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Arithmetic_CalculatorKeyPressed(evt);
            }
        });

        Quadretic_Equation_Solver.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Quadretic_Equation_Solver.setText("Quadratic Equation Solver");
        Quadretic_Equation_Solver.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Quadretic_Equation_Solver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Quadretic_Equation_Solver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Quadretic_Equation_SolverActionPerformed(evt);
            }
        });
        Quadretic_Equation_Solver.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Quadretic_Equation_SolverKeyPressed(evt);
            }
        });

        Trignometric_Calculator.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Trignometric_Calculator.setText("Trigonometric Calculator");
        Trignometric_Calculator.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Trignometric_Calculator.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Trignometric_Calculator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Trignometric_CalculatorActionPerformed(evt);
            }
        });
        Trignometric_Calculator.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Trignometric_CalculatorKeyPressed(evt);
            }
        });

        Geometric_Calculator.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Geometric_Calculator.setText("Geometric Calculator");
        Geometric_Calculator.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Geometric_Calculator.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Geometric_Calculator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Geometric_CalculatorActionPerformed(evt);
            }
        });
        Geometric_Calculator.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Geometric_CalculatorKeyPressed(evt);
            }
        });

        Unit_Convertor.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Unit_Convertor.setText("Unit Converter");
        Unit_Convertor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Unit_Convertor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Unit_Convertor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Unit_ConvertorActionPerformed(evt);
            }
        });
        Unit_Convertor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Unit_ConvertorKeyPressed(evt);
            }
        });

        Base_Convertor.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Base_Convertor.setText("Base Converter");
        Base_Convertor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Base_Convertor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Base_Convertor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Base_ConvertorMouseClicked(evt);
            }
        });
        Base_Convertor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Base_ConvertorActionPerformed(evt);
            }
        });
        Base_Convertor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Base_ConvertorKeyPressed(evt);
            }
        });

        Age_Calculator.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Age_Calculator.setText("Age Calculator");
        Age_Calculator.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Age_Calculator.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Age_Calculator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Age_CalculatorActionPerformed(evt);
            }
        });
        Age_Calculator.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Age_CalculatorKeyPressed(evt);
            }
        });

        Linear_Equation_Solver.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Linear_Equation_Solver.setText("Linear Equation Solver");
        Linear_Equation_Solver.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Linear_Equation_Solver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Linear_Equation_Solver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Linear_Equation_SolverActionPerformed(evt);
            }
        });
        Linear_Equation_Solver.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Linear_Equation_SolverKeyPressed(evt);
            }
        });

        Statistic_Calculator.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Statistic_Calculator.setText("Statistic Calculator");
        Statistic_Calculator.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Statistic_Calculator.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Statistic_Calculator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Statistic_CalculatorActionPerformed(evt);
            }
        });
        Statistic_Calculator.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Statistic_CalculatorKeyPressed(evt);
            }
        });

        Truth_Table_Designer.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Truth_Table_Designer.setText("Truth Table Designer");
        Truth_Table_Designer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Truth_Table_Designer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Truth_Table_Designer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Truth_Table_DesignerActionPerformed(evt);
            }
        });
        Truth_Table_Designer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Truth_Table_DesignerKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Age_Calculator)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                        .addComponent(Statistic_Calculator))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Arithmetic_Calculator)
                            .addComponent(Linear_Equation_Solver)
                            .addComponent(Geometric_Calculator)
                            .addComponent(Base_Convertor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Truth_Table_Designer, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Trignometric_Calculator, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Unit_Convertor, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Quadretic_Equation_Solver, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(34, 34, 34))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Age_Calculator, Arithmetic_Calculator, Base_Convertor, Geometric_Calculator, Linear_Equation_Solver, Quadretic_Equation_Solver, Statistic_Calculator, Trignometric_Calculator, Truth_Table_Designer, Unit_Convertor});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Arithmetic_Calculator, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Quadretic_Equation_Solver))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Age_Calculator)
                    .addComponent(Statistic_Calculator))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Base_Convertor)
                    .addComponent(Trignometric_Calculator))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Truth_Table_Designer)
                    .addComponent(Geometric_Calculator))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Unit_Convertor)
                    .addComponent(Linear_Equation_Solver))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Age_Calculator, Arithmetic_Calculator, Base_Convertor, Geometric_Calculator, Linear_Equation_Solver, Quadretic_Equation_Solver, Statistic_Calculator, Trignometric_Calculator, Truth_Table_Designer, Unit_Convertor});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Arithmetic_CalculatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Arithmetic_CalculatorActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Arithmetic_CalculatorActionPerformed

    private void Quadretic_Equation_SolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Quadretic_Equation_SolverActionPerformed
        // TODO add your handling code here:
        Quadratic_Equation_Solver obj=new Quadratic_Equation_Solver();
        obj.setVisible(true);
        CloseFrame();
    }//GEN-LAST:event_Quadretic_Equation_SolverActionPerformed

    private void Trignometric_CalculatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Trignometric_CalculatorActionPerformed
        // TODO add your handling code here:
        Trignometric_Calculator obj1=new Trignometric_Calculator();
        obj1.setVisible(true);
        CloseFrame();
    }//GEN-LAST:event_Trignometric_CalculatorActionPerformed

    private void Geometric_CalculatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Geometric_CalculatorActionPerformed
        // TODO add your handling code here:
        GeometricCalculator obj=new GeometricCalculator();
        obj.setVisible(true);
        CloseFrame();
    }//GEN-LAST:event_Geometric_CalculatorActionPerformed

    private void Unit_ConvertorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Unit_ConvertorActionPerformed
        // TODO add your handling code here:
        Unit_Convertor obj=new Unit_Convertor();
        obj.setVisible(true);
        CloseFrame();
    }//GEN-LAST:event_Unit_ConvertorActionPerformed

    private void Base_ConvertorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Base_ConvertorActionPerformed
        // TODO add your handling code here:
        Base_Convertor obj=new Base_Convertor();
        obj.setVisible(true);
        CloseFrame();
    }//GEN-LAST:event_Base_ConvertorActionPerformed

    private void Age_CalculatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Age_CalculatorActionPerformed
        // TODO add your handling code here:
        Age_Calculator obj=new Age_Calculator();
        obj.setVisible(true);
        CloseFrame();
    }//GEN-LAST:event_Age_CalculatorActionPerformed

    private void Linear_Equation_SolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Linear_Equation_SolverActionPerformed
        // TODO add your handling code here:
        Linear_Equation_Solver obj=new Linear_Equation_Solver();
        obj.setVisible(true);
        CloseFrame();
    }//GEN-LAST:event_Linear_Equation_SolverActionPerformed

    private void Statistic_CalculatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Statistic_CalculatorActionPerformed
        // TODO add your handling code here:
        Statistic_Calculator obj=new Statistic_Calculator();
        obj.setVisible(true);
        CloseFrame();
    }//GEN-LAST:event_Statistic_CalculatorActionPerformed

    private void Truth_Table_DesignerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Truth_Table_DesignerActionPerformed
        // TODO add your handling code here:
        Truth_Table_Designer obj=new Truth_Table_Designer();
        obj.setVisible(true);
        CloseFrame();
    }//GEN-LAST:event_Truth_Table_DesignerActionPerformed

    private void Arithmetic_CalculatorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Arithmetic_CalculatorMouseClicked
        // TODO add your handling code here:
        Arithmetic_Calculator obj1=new Arithmetic_Calculator();
        obj1.setVisible(true);
        CloseFrame();
    }//GEN-LAST:event_Arithmetic_CalculatorMouseClicked

    private void Arithmetic_CalculatorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Arithmetic_CalculatorKeyPressed
        // TODO add your handling code here:
        if((evt.getKeyChar()==10)){
            Arithmetic_Calculator obj1=new Arithmetic_Calculator();
            obj1.setVisible(true);
            CloseFrame();
        }
    }//GEN-LAST:event_Arithmetic_CalculatorKeyPressed

    private void Base_ConvertorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Base_ConvertorMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Base_ConvertorMouseClicked

    private void Base_ConvertorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Base_ConvertorKeyPressed
        // TODO add your handling code here:
        if((evt.getKeyChar()==10)){
            Base_Convertor obj=new Base_Convertor();
            obj.setVisible(true);
            CloseFrame();
        }
    }//GEN-LAST:event_Base_ConvertorKeyPressed

    private void Linear_Equation_SolverKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Linear_Equation_SolverKeyPressed
        // TODO add your handling code here:
        if((evt.getKeyChar()==10)){
            Linear_Equation_Solver obj=new Linear_Equation_Solver();
            obj.setVisible(true);
            CloseFrame();
        }
    }//GEN-LAST:event_Linear_Equation_SolverKeyPressed

    private void Quadretic_Equation_SolverKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Quadretic_Equation_SolverKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar()==10){
            Quadratic_Equation_Solver obj=new Quadratic_Equation_Solver();
            obj.setVisible(true);
            CloseFrame();
        }
    }//GEN-LAST:event_Quadretic_Equation_SolverKeyPressed

    private void Geometric_CalculatorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Geometric_CalculatorKeyPressed
        // TODO add your handling code here:
        if((evt.getKeyChar()==10)){
            GeometricCalculator obj=new GeometricCalculator();
            obj.setVisible(true);
            CloseFrame();
        }
    }//GEN-LAST:event_Geometric_CalculatorKeyPressed

    private void Unit_ConvertorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Unit_ConvertorKeyPressed
        // TODO add your handling code here:
        if((evt.getKeyChar()==10)){
            Unit_Convertor obj=new Unit_Convertor();
            obj.setVisible(true);
            CloseFrame();
        }
    }//GEN-LAST:event_Unit_ConvertorKeyPressed

    private void Statistic_CalculatorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Statistic_CalculatorKeyPressed
        // TODO add your handling code here:
        if((evt.getKeyChar()==10)){
            Statistic_Calculator obj=new Statistic_Calculator();
            obj.setVisible(true);
            CloseFrame();
        }
    }//GEN-LAST:event_Statistic_CalculatorKeyPressed

    private void Age_CalculatorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Age_CalculatorKeyPressed
        // TODO add your handling code here:
        if((evt.getKeyChar()==10)){
            Age_Calculator obj=new Age_Calculator();
            obj.setVisible(true);
            CloseFrame();
        }
    }//GEN-LAST:event_Age_CalculatorKeyPressed

    private void Trignometric_CalculatorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Trignometric_CalculatorKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar()==10){
            Trignometric_Calculator obj1=new Trignometric_Calculator();
            obj1.setVisible(true);
            CloseFrame();
        }
    }//GEN-LAST:event_Trignometric_CalculatorKeyPressed

    private void Truth_Table_DesignerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Truth_Table_DesignerKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar()==10){
            Truth_Table_Designer obj=new Truth_Table_Designer();
            obj.setVisible(true);
            CloseFrame();
        }
    }//GEN-LAST:event_Truth_Table_DesignerKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MAIN_MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MAIN_MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MAIN_MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MAIN_MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MAIN_MENU().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Age_Calculator;
    private javax.swing.JButton Arithmetic_Calculator;
    private javax.swing.JButton Base_Convertor;
    private javax.swing.JButton Geometric_Calculator;
    private javax.swing.JButton Linear_Equation_Solver;
    private javax.swing.JButton Quadretic_Equation_Solver;
    private javax.swing.JButton Statistic_Calculator;
    private javax.swing.JButton Trignometric_Calculator;
    private javax.swing.JButton Truth_Table_Designer;
    private javax.swing.JButton Unit_Convertor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void CloseFrame() {
        super.dispose();
    }
}
