
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HOME
 */
public class Parallalogram_Solver extends javax.swing.JFrame {

    /**
     * Creates new form Parallalogram_Solver
     */
    public Parallalogram_Solver() {
        initComponents();
        setVisible(true);
        setResizable(false);
        setTitle("PARALLELOGRAM SOLVER");
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        calculate = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        txt_Area = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txt_Perimeter = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_sideB = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_sideC = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_heightH = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 3, true));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 90)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Parallelogram Solver");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examples/parallelogram.gif"))); // NOI18N
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 240), 2, true));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("Reset");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        calculate.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        calculate.setText("Calculate");
        calculate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        calculate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calculateMouseClicked(evt);
            }
        });
        calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateActionPerformed(evt);
            }
        });
        calculate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                calculateFocusGained(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        txt_Area.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txt_Area.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_Area.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 240), 2, true));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_Area, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_Area, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        txt_Perimeter.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txt_Perimeter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_Perimeter.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 240), 2, true));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_Perimeter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_Perimeter, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Perimeter");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Area");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Side b");

        txt_sideB.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txt_sideB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_sideB.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 2, true));
        txt_sideB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_sideBMouseClicked(evt);
            }
        });
        txt_sideB.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_sideBFocusGained(evt);
            }
        });
        txt_sideB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_sideBKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Side c");

        txt_sideC.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txt_sideC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_sideC.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 2, true));
        txt_sideC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_sideCMouseClicked(evt);
            }
        });
        txt_sideC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_sideCFocusGained(evt);
            }
        });
        txt_sideC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_sideCKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Height h");

        txt_heightH.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txt_heightH.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_heightH.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 2, true));
        txt_heightH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_heightHMouseClicked(evt);
            }
        });
        txt_heightH.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_heightHFocusGained(evt);
            }
        });
        txt_heightH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_heightHKeyPressed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(153, 153, 255));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 102));
        jButton4.setText("Main Menu");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(153, 153, 255));
        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 102));
        jButton5.setText("Geometric Calculator");
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("Parallelogram Solver");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_sideB, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_sideC, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_heightH, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(calculate, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txt_sideB, txt_sideC});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {calculate, jButton2});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_sideB, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_sideC, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_heightH, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(calculate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel3, jLabel4, jLabel5, txt_heightH, txt_sideC});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        txt_sideB.setText("");
        txt_sideC.setText("");
        txt_heightH.setText("");
        txt_Area.setText("");
        txt_Perimeter.setText("");
        txt_sideB.setBackground(Color.WHITE);
        txt_sideC.setBackground(Color.WHITE);
        txt_heightH.setBackground(Color.WHITE);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_calculateActionPerformed

    private void txt_sideBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_sideBMouseClicked
        // TODO add your handling code here:
        txt_sideB.setBackground(Color.WHITE);
    }//GEN-LAST:event_txt_sideBMouseClicked

    private void txt_sideBFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_sideBFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sideBFocusGained

    private void txt_sideBKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_sideBKeyPressed
        // TODO add your handling code here:
        if ((evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || (evt.getKeyChar() == 8) || (evt.getKeyChar() == 10) || evt.getKeyChar()== '.'))  {
            int l=txt_sideB.getText().length();//System.out.println(len);
        if((l<=5) || (evt.getKeyChar()==8)){
            String value = txt_sideB.getText();
            if((evt.getKeyChar() == '.') && value.contains(".")){
                txt_sideB.setEditable(false);
            }
            else{
                txt_sideB.setEditable(true);
                if((evt.getKeyChar() == 10)){
                    if("".equals(txt_sideB.getText()) || "".equals(txt_sideC.getText()) || "".equals(txt_heightH.getText())){
                        if("".equals(txt_sideB.getText()) && "".equals(txt_sideC.getText()) && "".equals(txt_heightH.getText())){
                            JOptionPane.showMessageDialog(null,"PLEASE ENTER ALL THE SIDES OF PARALLELOGRAM");
                            txt_sideB.setBackground(Color.YELLOW);
                            txt_sideC.setBackground(Color.YELLOW);
                            txt_heightH.setBackground(Color.YELLOW);
                        }
                        else if("".equals(txt_sideB.getText()) && (!"".equals(txt_sideC.getText())) && (!"".equals(txt_heightH.getText()))){
                            JOptionPane.showMessageDialog(null,"PLEASE ENTER THE SIDE B OF PARALLELOGRAM");
                            txt_sideB.setBackground(Color.YELLOW);
                        }

                        else if("".equals(txt_sideC.getText()) && (!"".equals(txt_heightH.getText())) && (!"".equals(txt_sideB.getText()))){
                            JOptionPane.showMessageDialog(null,"PLEASE ENTER THE SIDE C OF PARALLELOGRAM");
                            txt_sideC.setBackground(Color.YELLOW);
                        }

                        else if("".equals(txt_heightH.getText()) && (!"".equals(txt_sideB.getText())) && (!"".equals(txt_sideC.getText()))){
                            JOptionPane.showMessageDialog(null,"PLEASE ENTER THE SIDE H OF PARALLELOGRAM");
                            txt_heightH.setBackground(Color.YELLOW);
                        }

                        else if("".equals(txt_sideB.getText()) && "".equals(txt_sideC.getText())){
                            JOptionPane.showMessageDialog(null,"PLEASE ENTER THE SIDES B AND C OF PARALLELOGRAM");
                            txt_sideB.setBackground(Color.YELLOW);
                            txt_sideC.setBackground(Color.YELLOW);
                        }

                        else if("".equals(txt_sideC.getText()) && "".equals(txt_heightH.getText())){
                            JOptionPane.showMessageDialog(null,"PLEASE ENTER THE SIDES C AND HEIGHT H OF PARALLELOGRAM");
                            txt_sideC.setBackground(Color.YELLOW);
                            txt_heightH.setBackground(Color.YELLOW);
                        }

                        else {
                            JOptionPane.showMessageDialog(null,"PLEASE ENTER THE SIDES B AND AND HEIGHT H OF PARALLELOGRAM");
                            txt_sideB.setBackground(Color.YELLOW);
                            txt_heightH.setBackground(Color.YELLOW);
                        }
                    }
                    else{
                        calculate.requestFocus();calculate.setFocusable(true);
                    }
                }
            }
        }
        else{
            txt_sideB.setEditable(false);
        }
        }
        else {
            txt_sideB.setEditable(false);
        }
    }//GEN-LAST:event_txt_sideBKeyPressed

    private void txt_sideCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_sideCMouseClicked
        // TODO add your handling code here:
        txt_sideC.setBackground(Color.WHITE);
    }//GEN-LAST:event_txt_sideCMouseClicked

    private void txt_sideCFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_sideCFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sideCFocusGained

    private void txt_sideCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_sideCKeyPressed
        // TODO add your handling code here:
        if ((evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || (evt.getKeyChar() == 8) || (evt.getKeyChar() == 10) || evt.getKeyChar()== '.'))  {
            int l=txt_sideC.getText().length();//System.out.println(len);
        if((l<=5) || (evt.getKeyChar()==8)){
            String value = txt_sideC.getText();
            if((evt.getKeyChar() == '.') && value.contains(".")){
                txt_sideC.setEditable(false);
            }
            else{
                txt_sideC.setEditable(true);
                if((evt.getKeyChar() == 10)){
                    if("".equals(txt_sideB.getText()) || "".equals(txt_sideC.getText()) || "".equals(txt_heightH.getText())){
                        if("".equals(txt_sideB.getText()) && "".equals(txt_sideC.getText()) && "".equals(txt_heightH.getText())){
                            JOptionPane.showMessageDialog(null,"PLEASE ENTER ALL THE SIDES OF PARALLELOGRAM");
                            txt_sideB.setBackground(Color.YELLOW);
                            txt_sideC.setBackground(Color.YELLOW);
                            txt_heightH.setBackground(Color.YELLOW);
                        }
                        else if("".equals(txt_sideB.getText()) && (!"".equals(txt_sideC.getText())) && (!"".equals(txt_heightH.getText()))){
                            JOptionPane.showMessageDialog(null,"PLEASE ENTER THE SIDE B OF PARALLELOGRAM");
                            txt_sideB.setBackground(Color.YELLOW);
                        }

                        else if("".equals(txt_sideC.getText()) && (!"".equals(txt_heightH.getText())) && (!"".equals(txt_sideB.getText()))){
                            JOptionPane.showMessageDialog(null,"PLEASE ENTER THE SIDE C OF PARALLELOGRAM");
                            txt_sideC.setBackground(Color.YELLOW);
                        }

                        else if("".equals(txt_heightH.getText()) && (!"".equals(txt_sideB.getText())) && (!"".equals(txt_sideC.getText()))){
                            JOptionPane.showMessageDialog(null,"PLEASE ENTER THE SIDE H OF PARALLELOGRAM");
                            txt_heightH.setBackground(Color.YELLOW);
                        }

                        else if("".equals(txt_sideB.getText()) && "".equals(txt_sideC.getText())){
                            JOptionPane.showMessageDialog(null,"PLEASE ENTER THE SIDES B AND C OF PARALLELOGRAM");
                            txt_sideB.setBackground(Color.YELLOW);
                            txt_sideC.setBackground(Color.YELLOW);
                        }

                        else if("".equals(txt_sideC.getText()) && "".equals(txt_heightH.getText())){
                            JOptionPane.showMessageDialog(null,"PLEASE ENTER THE SIDES C AND HEIGHT H OF PARALLELOGRAM");
                            txt_sideC.setBackground(Color.YELLOW);
                            txt_heightH.setBackground(Color.YELLOW);
                        }

                        else{
                            JOptionPane.showMessageDialog(null,"PLEASE ENTER THE SIDES B AND AND HEIGHT H OF PARALLELOGRAM");
                            txt_sideB.setBackground(Color.YELLOW);
                            txt_heightH.setBackground(Color.YELLOW);
                        }
                        
                    }
                    else{
                        calculate.requestFocus();calculate.setFocusable(true);
                    }
                }
            }
        }
        else{
            txt_sideC.setEditable(false);
        }
        }
        else {
            txt_sideC.setEditable(false);
        }
    }//GEN-LAST:event_txt_sideCKeyPressed

    private void txt_heightHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_heightHMouseClicked
        // TODO add your handling code here:
        txt_heightH.setBackground(Color.WHITE);
    }//GEN-LAST:event_txt_heightHMouseClicked

    private void txt_heightHFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_heightHFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_heightHFocusGained

    private void txt_heightHKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_heightHKeyPressed
        // TODO add your handling code here:
        if ((evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || (evt.getKeyChar() == 8) || (evt.getKeyChar() == 10) || evt.getKeyChar()== '.'))  {
            int l=txt_heightH.getText().length();//System.out.println(len);
        if((l<=5) || (evt.getKeyChar()==8)){
            String value = txt_heightH.getText();
            if((evt.getKeyChar() == '.') && value.contains(".")){
                txt_heightH.setEditable(false);
            }
            else{
                txt_heightH.setEditable(true);
                if((evt.getKeyChar() == 10)){
                    if("".equals(txt_sideB.getText()) || "".equals(txt_sideC.getText()) || "".equals(txt_heightH.getText())){
                        if("".equals(txt_sideB.getText()) && "".equals(txt_sideC.getText()) && "".equals(txt_heightH.getText())){
                            JOptionPane.showMessageDialog(null,"PLEASE ENTER ALL THE SIDES OF PARALLELOGRAM");
                            txt_sideB.setBackground(Color.YELLOW);
                            txt_sideC.setBackground(Color.YELLOW);
                            txt_heightH.setBackground(Color.YELLOW);
                        }
                        else if("".equals(txt_sideB.getText()) && (!"".equals(txt_sideC.getText())) && (!"".equals(txt_heightH.getText()))){
                            JOptionPane.showMessageDialog(null,"PLEASE ENTER THE SIDE B OF PARALLELOGRAM");
                            txt_sideB.setBackground(Color.YELLOW);
                        }

                        else if("".equals(txt_sideC.getText()) && (!"".equals(txt_heightH.getText())) && (!"".equals(txt_sideB.getText()))){
                            JOptionPane.showMessageDialog(null,"PLEASE ENTER THE SIDE C OF PARALLELOGRAM");
                            txt_sideC.setBackground(Color.YELLOW);
                        }

                        else if("".equals(txt_heightH.getText()) && (!"".equals(txt_sideB.getText())) && (!"".equals(txt_sideC.getText()))){
                            JOptionPane.showMessageDialog(null,"PLEASE ENTER THE SIDE H OF PARALLELOGRAM");
                            txt_heightH.setBackground(Color.YELLOW);
                        }

                        else if("".equals(txt_sideB.getText()) && "".equals(txt_sideC.getText())){
                            JOptionPane.showMessageDialog(null,"PLEASE ENTER THE SIDES B AND C OF PARALLELOGRAM");
                            txt_sideB.setBackground(Color.YELLOW);
                            txt_sideC.setBackground(Color.YELLOW);
                        }

                        else if("".equals(txt_sideC.getText()) && "".equals(txt_heightH.getText())){
                            JOptionPane.showMessageDialog(null,"PLEASE ENTER THE SIDES C AND HEIGHT H OF PARALLELOGRAM");
                            txt_sideC.setBackground(Color.YELLOW);
                            txt_heightH.setBackground(Color.YELLOW);
                        }

                        else{
                            JOptionPane.showMessageDialog(null,"PLEASE ENTER THE SIDES B AND AND HEIGHT H OF PARALLELOGRAM");
                            txt_sideB.setBackground(Color.YELLOW);
                            txt_heightH.setBackground(Color.YELLOW);
                        }
                        
                    }
                    else{
                        calculate.requestFocus();calculate.setFocusable(true);
                    }
                }
            }
        }
        else{
            txt_heightH.setEditable(false);
        }
        }
        else {
            txt_heightH.setEditable(false);
        }
    }//GEN-LAST:event_txt_heightHKeyPressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        MAIN_MENU obj=new MAIN_MENU();
        obj.setVisible(true);
        CloseFrame();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        GeometricCalculator obj=new GeometricCalculator();
        obj.setVisible(true);
        CloseFrame();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void calculateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_calculateFocusGained
        // TODO add your handling code here:
        if("".equals(txt_sideB.getText()) || "".equals(txt_sideC.getText()) || "".equals(txt_heightH.getText())){}
        else{
        float area=0,perimeter=0;
        String type=null;
        String status=null;
        txt_Area.setText("");
        txt_Perimeter.setText("");
        float input_sideB=Float.parseFloat(txt_sideB.getText());
        float input_sideC=Float.parseFloat(txt_sideC.getText());
        float input_heightH=Float.parseFloat(txt_heightH.getText());
        ParallelogramSolver obj=new ParallelogramSolver(input_sideB,input_sideC,input_heightH);
        perimeter=obj.computeParimeter ();
        area=obj.computeArea ();
        txt_Area.setText(String.valueOf(area));
        txt_Perimeter.setText(String.valueOf(perimeter));   
        }
    }//GEN-LAST:event_calculateFocusGained

    private void calculateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calculateMouseClicked
        // TODO add your handling code here:
        float area=0,perimeter=0;
        String type=null;
        String status=null;
        txt_Area.setText("");
        txt_Perimeter.setText("");

         if("".equals(txt_sideB.getText()) || "".equals(txt_sideC.getText()) || "".equals(txt_heightH.getText())){
            if("".equals(txt_sideB.getText()) && "".equals(txt_sideC.getText()) && "".equals(txt_heightH.getText())){
                JOptionPane.showMessageDialog(null,"PLEASE ENTER ALL THE SIDES OF PARALLELOGRAM");
                txt_sideB.setBackground(Color.YELLOW);
                txt_sideC.setBackground(Color.YELLOW);
                txt_heightH.setBackground(Color.YELLOW);
            }

            else if("".equals(txt_sideB.getText()) && (!"".equals(txt_sideC.getText())) && (!"".equals(txt_heightH.getText()))){
                JOptionPane.showMessageDialog(null,"PLEASE ENTER THE SIDE B OF PARALLELOGRAM");
                txt_sideB.setBackground(Color.YELLOW);
            }

            else if("".equals(txt_sideC.getText()) && (!"".equals(txt_heightH.getText())) && (!"".equals(txt_sideB.getText()))){
                JOptionPane.showMessageDialog(null,"PLEASE ENTER THE SIDE B OF PARALLELGRAM");
                txt_sideC.setBackground(Color.YELLOW);
            }

            else if("".equals(txt_heightH.getText()) && (!"".equals(txt_sideB.getText())) && (!"".equals(txt_sideC.getText()))){
                JOptionPane.showMessageDialog(null,"PLEASE ENTER THE SIDE C OF PARALLELGRAM");
                txt_heightH.setBackground(Color.YELLOW);
            }

            else if("".equals(txt_sideB.getText()) && "".equals(txt_sideC.getText())){
                JOptionPane.showMessageDialog(null,"PLEASE ENTER THE SIDES B AND C OF PARALLELGRAM");
                txt_sideB.setBackground(Color.YELLOW);
                txt_sideC.setBackground(Color.YELLOW);
            }

            else if("".equals(txt_sideC.getText()) && "".equals(txt_heightH.getText())){
                JOptionPane.showMessageDialog(null,"PLEASE ENTER THE SIDES C AND HEIGHT H OF PARALLELGRAM");
                txt_sideC.setBackground(Color.YELLOW);
                txt_heightH.setBackground(Color.YELLOW);
            }

            else{
                JOptionPane.showMessageDialog(null,"PLEASE ENTER THE SIDES B AND HEIGHT H OF PARALLELGRAM");
                txt_sideB.setBackground(Color.YELLOW);
                txt_heightH.setBackground(Color.YELLOW);
            }
        }

        else{
            float input_sideB=Float.parseFloat(txt_sideB.getText());
            float input_sideC=Float.parseFloat(txt_sideC.getText());
            float input_heightH=Float.parseFloat(txt_heightH.getText());
            ParallelogramSolver obj=new ParallelogramSolver(input_sideB,input_sideC,input_heightH);
            perimeter=obj.computeParimeter ();
            area=obj.computeArea ();
            txt_Area.setText(String.valueOf(area));
            txt_Perimeter.setText(String.valueOf(perimeter));
       }
    }//GEN-LAST:event_calculateMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Parallalogram_Solver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Parallalogram_Solver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Parallalogram_Solver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Parallalogram_Solver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Parallalogram_Solver().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculate;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel txt_Area;
    private javax.swing.JLabel txt_Perimeter;
    private javax.swing.JTextField txt_heightH;
    private javax.swing.JTextField txt_sideB;
    private javax.swing.JTextField txt_sideC;
    // End of variables declaration//GEN-END:variables

    private void CloseFrame() {
        super.dispose();
    }
}
