
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HOME
 */
public class Triangle_Solver extends javax.swing.JFrame {

    /**
     * Creates new form Triangle_Solver
     */
    public Triangle_Solver() {
        initComponents();
        setVisible(true);
        setResizable(false);
        setTitle("TRIANGLE SOLVER");
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_sideA = new javax.swing.JTextField();
        txt_sideB = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_sideC = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txt_Status = new javax.swing.JLabel();
        calculate = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txt_type = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txt_Area = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txt_Perimeter = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 3, true));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 90)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Triangle Solver");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examples/Triangle1.png"))); // NOI18N
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 240), 2, true));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Side A");

        txt_sideA.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txt_sideA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_sideA.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 2, true));
        txt_sideA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_sideAMouseClicked(evt);
            }
        });
        txt_sideA.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_sideAFocusGained(evt);
            }
        });
        txt_sideA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_sideAKeyPressed(evt);
            }
        });

        txt_sideB.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txt_sideB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_sideB.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 2, true));
        txt_sideB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_sideBMouseClicked(evt);
            }
        });
        txt_sideB.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_sideBFocusGained(evt);
            }
        });
        txt_sideB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_sideBKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Side B");

        txt_sideC.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txt_sideC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_sideC.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 2, true));
        txt_sideC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_sideCMouseClicked(evt);
            }
        });
        txt_sideC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_sideCFocusGained(evt);
            }
        });
        txt_sideC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_sideCKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Side C");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        txt_Status.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txt_Status.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 240), 2, true));

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, txt_Status, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                .add(0, 0, Short.MAX_VALUE)
                .add(txt_Status, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        calculate.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        calculate.setText("Calculate");
        calculate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        calculate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        calculate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calculateMouseClicked(evt);
            }
        });
        calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateActionPerformed(evt);
            }
        });
        calculate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                calculateFocusGained(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("Reset");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        txt_type.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txt_type.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_type.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 240), 2, true));

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, txt_type, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(txt_type, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Type");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Area");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        txt_Area.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txt_Area.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_Area.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 240), 2, true));

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, txt_Area, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(txt_Area, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Perimeter");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        txt_Perimeter.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txt_Perimeter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_Perimeter.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 240), 2, true));

        org.jdesktop.layout.GroupLayout jPanel5Layout = new org.jdesktop.layout.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, txt_Perimeter, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(txt_Perimeter, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Status :");

        jButton4.setBackground(new java.awt.Color(153, 153, 255));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 102));
        jButton4.setText("Main Menu");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(153, 153, 255));
        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 102));
        jButton5.setText("Geometric Calculator");
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 102));
        jLabel10.setText("Triangle Solver");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel2)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(29, 29, 29)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel9)
                            .add(jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 75, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(jLabel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 53, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(jLabel8))
                                        .add(64, 64, 64)
                                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .add(jPanel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .add(jPanel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(calculate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 241, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                        .add(jButton2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                            .add(txt_sideA)
                                            .add(jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                                        .add(29, 29, 29)
                                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                            .add(txt_sideB)
                                            .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 28, Short.MAX_VALUE)
                                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(txt_sideC, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 137, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap())))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(10, 10, 10)
                        .add(jButton4)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton5)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel10)
                        .add(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 83, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jButton4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel10, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jButton5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(7, 7, 7)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                .add(txt_sideC, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(jPanel1Layout.createSequentialGroup()
                                    .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(txt_sideA, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                            .add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(txt_sideB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jButton2)
                            .add(calculate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 36, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(9, 9, 9)
                        .add(jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jLabel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jLabel8, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jLabel9, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jPanel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(20, 20, 20))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jLabel2)
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel1Layout.linkSize(new java.awt.Component[] {calculate, jButton2}, org.jdesktop.layout.GroupLayout.VERTICAL);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_sideAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_sideAMouseClicked
        // TODO add your handling code here:
        txt_sideA.setBackground(Color.WHITE);
    }//GEN-LAST:event_txt_sideAMouseClicked

    private void txt_sideAFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_sideAFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sideAFocusGained

    private void txt_sideAKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_sideAKeyPressed
        // TODO add your handling code here:
        if ((evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || (evt.getKeyChar() == 8) || (evt.getKeyChar()==10) || evt.getKeyChar()== '.'))  {
            int l=txt_sideA.getText().length();//System.out.println(len);
        if((l<=5) || (evt.getKeyChar()==8)){
            String value = txt_sideA.getText();
            if((evt.getKeyChar() == '.') && value.contains(".")){
                txt_sideA.setEditable(false);
            }
            else{
                txt_sideA.setEditable(true);
                if((evt.getKeyChar() == 10)){
                    if("".equals(txt_sideA.getText()) || "".equals(txt_sideB.getText()) || "".equals(txt_sideC.getText())){
                        if("".equals(txt_sideA.getText()) && "".equals(txt_sideB.getText()) && "".equals(txt_sideC.getText())){
                            JOptionPane.showMessageDialog(null,"PLEASE ENTER ALL THE SIDES OF TRIANGLE");
                            txt_sideA.setBackground(Color.YELLOW);
                            txt_sideB.setBackground(Color.YELLOW);
                            txt_sideC.setBackground(Color.YELLOW);
                            }

                        else if("".equals(txt_sideA.getText()) && (!"".equals(txt_sideB.getText())) && (!"".equals(txt_sideC.getText()))){
                            JOptionPane.showMessageDialog(null,"PLEASE ENTER THE SIDE A OF TRIANGLE");
                            txt_sideA.setBackground(Color.YELLOW);
                        }

                        else if("".equals(txt_sideB.getText()) && (!"".equals(txt_sideC.getText())) && (!"".equals(txt_sideA.getText()))){
                            JOptionPane.showMessageDialog(null,"PLEASE ENTER THE SIDE B OF TRIANGLE");
                            txt_sideB.setBackground(Color.YELLOW);
                        }

                        else if("".equals(txt_sideC.getText()) && (!"".equals(txt_sideA.getText())) && (!"".equals(txt_sideB.getText()))){
                            JOptionPane.showMessageDialog(null,"PLEASE ENTER THE SIDE C OF TRIANGLE");
                            txt_sideC.setBackground(Color.YELLOW);
                        }

                        else if("".equals(txt_sideA.getText()) && "".equals(txt_sideB.getText())){
                            JOptionPane.showMessageDialog(null,"PLEASE ENTER THE SIDES A AND B OF TRIANGLE");
                            txt_sideA.setBackground(Color.YELLOW);
                            txt_sideB.setBackground(Color.YELLOW);
                        }

                        else if("".equals(txt_sideB.getText()) && "".equals(txt_sideC.getText())){
                            JOptionPane.showMessageDialog(null,"PLEASE ENTER THE SIDES B AND C OF TRIANGLE");
                            txt_sideB.setBackground(Color.YELLOW);
                            txt_sideC.setBackground(Color.YELLOW);
                        }

                        else{
                            JOptionPane.showMessageDialog(null,"PLEASE ENTER THE SIDES A AND C OF TRIANGLE");
                            txt_sideA.setBackground(Color.YELLOW);
                            txt_sideC.setBackground(Color.YELLOW);
                        }
                    }
                    else{
                        calculate.requestFocus();calculate.setFocusable(true);
                    }
                }
                
            }
        }
        else{
            txt_sideA.setEditable(false);
        }
        }
        else {
            txt_sideA.setEditable(false);
        }
    }//GEN-LAST:event_txt_sideAKeyPressed

    private void txt_sideBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_sideBMouseClicked
        // TODO add your handling code here:
        txt_sideB.setBackground(Color.WHITE);
    }//GEN-LAST:event_txt_sideBMouseClicked

    private void txt_sideBFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_sideBFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sideBFocusGained

    private void txt_sideBKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_sideBKeyPressed
        // TODO add your handling code here:
        if ((evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || (evt.getKeyChar() == 8) || (evt.getKeyChar()==10) || evt.getKeyChar()== '.'))  {
            int l=txt_sideB.getText().length();//System.out.println(len);
        if((l<=9) || (evt.getKeyChar()==8)){
            String value = txt_sideB.getText();
            if((evt.getKeyChar() == '.') && value.contains(".")){
                txt_sideB.setEditable(false);
            }
            else{
                txt_sideB.setEditable(true);
                if((evt.getKeyChar() == 10)){
                    if("".equals(txt_sideA.getText()) || "".equals(txt_sideB.getText()) || "".equals(txt_sideC.getText())){
                        if("".equals(txt_sideA.getText()) && "".equals(txt_sideB.getText()) && "".equals(txt_sideC.getText())){
                            JOptionPane.showMessageDialog(null,"PLEASE ENTER ALL THE SIDES OF TRIANGLE");
                            txt_sideA.setBackground(Color.YELLOW);
                            txt_sideB.setBackground(Color.YELLOW);
                            txt_sideC.setBackground(Color.YELLOW);
                            }

                        else if("".equals(txt_sideA.getText()) && (!"".equals(txt_sideB.getText())) && (!"".equals(txt_sideC.getText()))){
                            JOptionPane.showMessageDialog(null,"PLEASE ENTER THE SIDE A OF TRIANGLE");
                            txt_sideA.setBackground(Color.YELLOW);
                        }

                        else if("".equals(txt_sideB.getText()) && (!"".equals(txt_sideC.getText())) && (!"".equals(txt_sideA.getText()))){
                            JOptionPane.showMessageDialog(null,"PLEASE ENTER THE SIDE B OF TRIANGLE");
                            txt_sideB.setBackground(Color.YELLOW);
                        }

                        else if("".equals(txt_sideC.getText()) && (!"".equals(txt_sideA.getText())) && (!"".equals(txt_sideB.getText()))){
                            JOptionPane.showMessageDialog(null,"PLEASE ENTER THE SIDE C OF TRIANGLE");
                            txt_sideC.setBackground(Color.YELLOW);
                        }

                        else if("".equals(txt_sideA.getText()) && "".equals(txt_sideB.getText())){
                            JOptionPane.showMessageDialog(null,"PLEASE ENTER THE SIDES A AND B OF TRIANGLE");
                            txt_sideA.setBackground(Color.YELLOW);
                            txt_sideB.setBackground(Color.YELLOW);
                        }

                        else if("".equals(txt_sideB.getText()) && "".equals(txt_sideC.getText())){
                            JOptionPane.showMessageDialog(null,"PLEASE ENTER THE SIDES B AND C OF TRIANGLE");
                            txt_sideB.setBackground(Color.YELLOW);
                            txt_sideC.setBackground(Color.YELLOW);
                        }

                        else{
                            JOptionPane.showMessageDialog(null,"PLEASE ENTER THE SIDES A AND C OF TRIANGLE");
                            txt_sideA.setBackground(Color.YELLOW);
                            txt_sideC.setBackground(Color.YELLOW);
                        }
                    }
                    else{
                        calculate.requestFocus();calculate.setFocusable(true);
                    }
                }
            }
        }
        else{
            txt_sideB.setEditable(false);
        }
        }
        else {
            txt_sideB.setEditable(false);
        }
    }//GEN-LAST:event_txt_sideBKeyPressed

    private void txt_sideCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_sideCMouseClicked
        // TODO add your handling code here:
        txt_sideC.setBackground(Color.WHITE);
    }//GEN-LAST:event_txt_sideCMouseClicked

    private void txt_sideCFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_sideCFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sideCFocusGained

    private void txt_sideCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_sideCKeyPressed
        // TODO add your handling code here:
        if ((evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || (evt.getKeyChar() == 8) || (evt.getKeyChar()==10) || evt.getKeyChar()== '.'))  {
            int l=txt_sideC.getText().length();//System.out.println(len);
        if((l<=9) || (evt.getKeyChar()==8)){
            String value = txt_sideC.getText();
            if((evt.getKeyChar() == '.') && value.contains(".")){
                txt_sideC.setEditable(false);
            }
            else{
                txt_sideC.setEditable(true);
                if((evt.getKeyChar() == 10)){
                    if("".equals(txt_sideA.getText()) || "".equals(txt_sideB.getText()) || "".equals(txt_sideC.getText())){
                        if("".equals(txt_sideA.getText()) && "".equals(txt_sideB.getText()) && "".equals(txt_sideC.getText())){
                            JOptionPane.showMessageDialog(null,"PLEASE ENTER ALL THE SIDES OF TRIANGLE");
                            txt_sideA.setBackground(Color.YELLOW);
                            txt_sideB.setBackground(Color.YELLOW);
                            txt_sideC.setBackground(Color.YELLOW);
                            }

                        else if("".equals(txt_sideA.getText()) && (!"".equals(txt_sideB.getText())) && (!"".equals(txt_sideC.getText()))){
                            JOptionPane.showMessageDialog(null,"PLEASE ENTER THE SIDE A OF TRIANGLE");
                            txt_sideA.setBackground(Color.YELLOW);
                        }

                        else if("".equals(txt_sideB.getText()) && (!"".equals(txt_sideC.getText())) && (!"".equals(txt_sideA.getText()))){
                            JOptionPane.showMessageDialog(null,"PLEASE ENTER THE SIDE B OF TRIANGLE");
                            txt_sideB.setBackground(Color.YELLOW);
                        }

                        else if("".equals(txt_sideC.getText()) && (!"".equals(txt_sideA.getText())) && (!"".equals(txt_sideB.getText()))){
                            JOptionPane.showMessageDialog(null,"PLEASE ENTER THE SIDE C OF TRIANGLE");
                            txt_sideC.setBackground(Color.YELLOW);
                        }

                        else if("".equals(txt_sideA.getText()) && "".equals(txt_sideB.getText())){
                            JOptionPane.showMessageDialog(null,"PLEASE ENTER THE SIDES A AND B OF TRIANGLE");
                            txt_sideA.setBackground(Color.YELLOW);
                            txt_sideB.setBackground(Color.YELLOW);
                        }

                        else if("".equals(txt_sideB.getText()) && "".equals(txt_sideC.getText())){
                            JOptionPane.showMessageDialog(null,"PLEASE ENTER THE SIDES B AND C OF TRIANGLE");
                            txt_sideB.setBackground(Color.YELLOW);
                            txt_sideC.setBackground(Color.YELLOW);
                        }

                        else{
                            JOptionPane.showMessageDialog(null,"PLEASE ENTER THE SIDES A AND C OF TRIANGLE");
                            txt_sideA.setBackground(Color.YELLOW);
                            txt_sideC.setBackground(Color.YELLOW);
                        }
                    }
                    else{
                        calculate.requestFocus();calculate.setFocusable(true);
                    }
                }
            }
        }
        else{
            txt_sideC.setEditable(false);
        }
        }
        else {
            txt_sideC.setEditable(false);
        }
    }//GEN-LAST:event_txt_sideCKeyPressed

    private void calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_calculateActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        txt_sideA.setText("");
        txt_sideB.setText("");
        txt_sideC.setText("");
        txt_type.setText("");
        txt_Area.setText("");
        txt_Perimeter.setText("");
        txt_Status.setText("");
        txt_sideA.setBackground(Color.WHITE);
        txt_sideB.setBackground(Color.WHITE);
        txt_sideC.setBackground(Color.WHITE);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        MAIN_MENU obj=new MAIN_MENU();
        obj.setVisible(true);
        CloseFrame();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        GeometricCalculator obj=new GeometricCalculator();
        obj.setVisible(true);
        CloseFrame();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void calculateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calculateMouseClicked
        // TODO add your handling code here:
        float area=0,perimeter=0;
        String type=null;
        String status=null;
        txt_Status.setText("");
        txt_Area.setText("");
        txt_Perimeter.setText("");
        txt_type.setText("");

        if("".equals(txt_sideA.getText()) || "".equals(txt_sideB.getText()) || "".equals(txt_sideC.getText())){
            if("".equals(txt_sideA.getText()) && "".equals(txt_sideB.getText()) && "".equals(txt_sideC.getText())){
                JOptionPane.showMessageDialog(null,"PLEASE ENTER ALL THE SIDES OF TRIANGLE");
                txt_sideA.setBackground(Color.YELLOW);
                txt_sideB.setBackground(Color.YELLOW);
                txt_sideC.setBackground(Color.YELLOW);
            }

            else if("".equals(txt_sideA.getText()) && (!"".equals(txt_sideB.getText())) && (!"".equals(txt_sideC.getText()))){
                JOptionPane.showMessageDialog(null,"PLEASE ENTER THE SIDE A OF TRIANGLE");
                txt_sideA.setBackground(Color.YELLOW);
            }

            else if("".equals(txt_sideB.getText()) && (!"".equals(txt_sideC.getText())) && (!"".equals(txt_sideA.getText()))){
                JOptionPane.showMessageDialog(null,"PLEASE ENTER THE SIDE B OF TRIANGLE");
                txt_sideB.setBackground(Color.YELLOW);
            }

            else if("".equals(txt_sideC.getText()) && (!"".equals(txt_sideA.getText())) && (!"".equals(txt_sideB.getText()))){
                JOptionPane.showMessageDialog(null,"PLEASE ENTER THE SIDE C OF TRIANGLE");
                txt_sideC.setBackground(Color.YELLOW);
            }

            else if("".equals(txt_sideA.getText()) && "".equals(txt_sideB.getText())){
                JOptionPane.showMessageDialog(null,"PLEASE ENTER THE SIDES A AND B OF TRIANGLE");
                txt_sideA.setBackground(Color.YELLOW);
                txt_sideB.setBackground(Color.YELLOW);
            }

            else if("".equals(txt_sideB.getText()) && "".equals(txt_sideC.getText())){
                JOptionPane.showMessageDialog(null,"PLEASE ENTER THE SIDES B AND C OF TRIANGLE");
                txt_sideB.setBackground(Color.YELLOW);
                txt_sideC.setBackground(Color.YELLOW);
            }

            else{
                JOptionPane.showMessageDialog(null,"PLEASE ENTER THE SIDES A AND C OF TRIANGLE");
                txt_sideA.setBackground(Color.YELLOW);
                txt_sideC.setBackground(Color.YELLOW);
            }
        }

        else{
            float input_sideA=Float.parseFloat(txt_sideA.getText());
            float input_sideB=Float.parseFloat(txt_sideB.getText());
            float input_sideC=Float.parseFloat(txt_sideC.getText());
            TriangleSolver obj=new TriangleSolver(input_sideA,input_sideB,input_sideC);
            status=obj.Triangle_inequality_theorem();
            if("Successfully, able to create a triangle".equals(status)){
                perimeter=obj.computeParimeter ();
                area=obj.computeArea ();
                type=obj.computeType ();
                txt_Status.setText(txt_Status.getText()+status);
                txt_Area.setText(String.valueOf(area));
                txt_Perimeter.setText(String.valueOf(perimeter));
                txt_type.setText(String.valueOf(type));
            }
            else{
                txt_Status.setText(txt_Status.getText()+status);
            }
        }
    }//GEN-LAST:event_calculateMouseClicked

    private void calculateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_calculateFocusGained
        // TODO add your handling code here:
        if("".equals(txt_sideA.getText()) || "".equals(txt_sideB.getText()) || "".equals(txt_sideC.getText())){}
        else{
            float area=0,perimeter=0;
            String type=null;
            String status=null;
            txt_Status.setText("");
            txt_Area.setText("");
            txt_Perimeter.setText("");
            txt_type.setText("");
            float input_sideA=Float.parseFloat(txt_sideA.getText());
            float input_sideB=Float.parseFloat(txt_sideB.getText());
            float input_sideC=Float.parseFloat(txt_sideC.getText());
            TriangleSolver obj=new TriangleSolver(input_sideA,input_sideB,input_sideC);
            status=obj.Triangle_inequality_theorem();
            if("Successfully, able to create a triangle".equals(status)){
                perimeter=obj.computeParimeter ();
                area=obj.computeArea ();
                type=obj.computeType ();
                txt_Status.setText(txt_Status.getText()+status);
                txt_Area.setText(String.valueOf(area));
                txt_Perimeter.setText(String.valueOf(perimeter));
                txt_type.setText(String.valueOf(type));
            }
            else{
                txt_Status.setText(txt_Status.getText()+status);
            }
        }
    }//GEN-LAST:event_calculateFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Triangle_Solver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Triangle_Solver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Triangle_Solver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Triangle_Solver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Triangle_Solver().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculate;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel txt_Area;
    private javax.swing.JLabel txt_Perimeter;
    private javax.swing.JLabel txt_Status;
    private javax.swing.JTextField txt_sideA;
    private javax.swing.JTextField txt_sideB;
    private javax.swing.JTextField txt_sideC;
    private javax.swing.JLabel txt_type;
    // End of variables declaration//GEN-END:variables

    private void CloseFrame() {
        super.dispose();
    }
}
